### ISSUE TITLE
Implement Mesh networking

### ISSUE THREAD

**Issue by bs-github** [warp-more-hardware/esp32-firmware#11]
**I'd like to have mesh networking for the ESP32 WiFi.**
Less infrastructure is less maintenance and a lower investment in the first place.
Therefore I'd like to have the capability of a bunch of WARP chargers to form a WiFi mesh network and utilise that to do load management.

**The solution I'd like**
I'd like to have the ESP32 run in AP+STA mode and build a WiFi MESH to form a load management setup that spans a bigger area easily.
https://www.espressif.com/en/products/sdks/esp-wifi-mesh/overview

**Alternatives**
More hardware. I.e. WiFi access points.
Obviously possible, but not desirable.

**Additional context**
The ESP32 in Access point mode by default can have only 4 WiFi clients. This limit can be upped to 10 at compile time. That is not enough and does not scale in two dimensions.
1. Number of WIFI devices obviously. If, in addition to multiple WARP chargers, mobile devices as clients to access the web ui come into play, 4-10 is surely enough for one charger, but not a load management setup.
2. Geographical expanse. The WiFi range of the ESP32 is limited and a parking lot can easily span a larger area and therefore extending the WiFi coverage would be a big plus as well.

**Comment by bs-github** [comment]
There might be an issue with access to the web interface of a particular member of the mesh network.

I'm not sure how exactly the MESH works, but we need to make sure that the user is still able to select one particular box and connect to it to access the web user interface of that particular box.

**Comment by michelepagot** [comment]
Some reading:
 * https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/esp-wifi-mesh.html
 * https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/network/esp-wifi-mesh.html?highlight=mesh

Some repo to check:
 * https://github.com/espressif/esp-mdf
 * https://gitlab.com/painlessMesh/painlessMesh

**Comment by michelepagot** [comment]
## PainlessMesh vs ESP-WIFI-MESH

### PainlessMesh
Example project [mesh-mash/painlessmesh](https://github.com/michelepagot/mesh-mash/tree/main/painlessmesh)

#### Pro:
 - Easy to integrate in PlatformIO (very easy)
 - Easy to use API. Create a working demo was few hours work.
 - Easy to understand internal architecture and implementation
 - Easy to debug and follow at runtime
 - Support: This library is well adopted by the community and the maintainer is actively monitoring merge requests. The project is community driven.

#### Cons:
 - Configuration of the MESH is limited.
 - Not top level documentation. There's a good base but there are some features that are not documented at all.
 - Integration in the existing FW quite like need more work in the existing codebase.
 - API stability: it has releases but weak than ESP-IDF.


### ESP-WIFI-MESH
Example project [mesh-mash/esp-wifi-mesh](https://github.com/michelepagot/mesh-mash/tree/main/esp-wifi-mesh)

#### Pro:
 - Super configurable
 - Feature rich
 - Professional documentation
 - Easy to debug and follow at runtime
 - Support: Espressif provide it.

#### Cons:
 - Complex API. More code also for simple MESH.
 - Only for ESP-IDF buildsystem out of the box

**Comment by bs-github** [comment]
We concluded, that this is not worth the effort for now.

PainlessMesh needs to much changes in the TinkerForge firmware architecture, and  
ESP-WIFI-MESH might work in that regard, but is not supported by PlatformIO.

Reinventing the wheel (starting from scratch) is not a viable option as well.
