### ISSUE TITLE
Charging starts in spite of Autostart = off

### ISSUE THREAD

**Issue by lucky2k12** [warp-more-hardware/esp32-firmware#40]
## Describe the bug

Charging starts in spite of Autostart = off when plugging car in. (No start button pressed)

## To Reproduce

1. The LED stripe on the charger where blinking green.
2. I plugged the charge cable into the car.
3. The car started to charge and
4. hitting Stop did not work either, I had to stop the charge by using the cars app

## Expected behavior

If autocharge is of the car shouldn't start charging by itself.

## Versions:

- Firmware version: 2.0.11-63e237d2 
- Make and model of the car do you want to charge: MG4 electric

[debug-report-AC011K-10052201194085-2023-02-07T14-27-58-429.txt](https://github.com/warp-more-hardware/esp32-firmware/files/10675537/debug-report-AC011K-10052201194085-2023-02-07T14-27-58-429.txt)

**Comment by lucky2k12** [comment]
solved, since the autostart-jumper was set, once set to off the Start/Stop buttons also work in the GUI.
Sorry for the hassle°

**Comment by bs-github** [comment]
Ich hab diesen Kommentar vorher gestartet, bin aber mit dem posten nicht schnell genug gewesen. 
Dennoch wollte ich das hier lassen damit es vielleicht anderen hilft...

In deinem Log sind mir folgende Dinge aufgefallen:  
`  2023-02-07 14:19:32,906  EVSE GD Status now 3: Charging (charging ongoing, power output), allowed charging current 0mA`
Da hat der Ladevorgang schon begonnen bevor die WARP Firmware auf dem ESP fertig gestartet hat.

Die WARP Firmware sendet gar keinen Start/Stop.

Hast du bei schon laufender Ladung die neue Firmware geflasht?

Wenn nicht, dann sieht mir das doch sehr nach dem Jumper CN7 an der falschen Position aus.  
Ich hab diesbezüglich noch die Dokumentation ergänzt: 

`  2023-02-07 14:19:37,797  set - slot 8: max_current: 32000, active: true, clear_on_disconnect: false`
Sieht so aus als wenn Lastmanagement aktiviert ist. Ist das Absicht?

`  2023-02-07 14:24:46,557  Charger state changed from 3 to 2`
Stop der Ladung (vom Auto initiiert)

`  2023-02-07 14:26:51,460  EVSE GD Status now 3: Charging (charging ongoing, power output), allowed charging current 0mA`
`  2023-02-07 14:26:51,594  Charger state changed from 2 to 3`
Auch am Ende des Logs lädt das Auto weiter (auch wenn es zwischendurch  gestoppt hat).

Bitte mal die Box stromlos machen und wieder einschalten (um den GD chip neu zu starten).
Wenn das nichts ändert, bitte den Jumper CN7 prüfen.

https://github.com/warp-more-hardware/esp32-firmware/wiki#betriebsarten-der-ac011k-wallbox
