### ISSUE TITLE
all states zero in release 2.0.12

### ISSUE THREAD

**Issue by stpmuspro** [warp-more-hardware/esp32-firmware#53]
## Describe the bug

Nach Einspielen der 2.0.12 blinkt die Wallbox bei verbundenem Fahrzeug nur noch gelb.
Statusseite zeigt keine Änderung - dauerhaft getrennt - MQTT evse/state - 

{"iec61851_state":0,"charger_state":0,"GD_state":0,"contactor_state":0,"contactor_error":0,"allowed_charging_current":16000,"error_state":0,"lock_state":0,"dc_fault_current_state":0,"time_since_state_change":155123,"last_state_change":0}

1.2.99 funktioniert.

## To Reproduce

Hab jetzt mehrere Versuche durch:
EN+ von Entratek (DOT Eco)
ausgeliefert mit GD-Version 1.1.888

1.2.99 geflashed - läuft wie gedacht.
OTAUpdate auf 2.0.12 - Fehler wie oben beschrieben.

Zurück auf Herstellerfirmware - läuft. Schnell noch eine RFID-Karte gelöscht, da vergessen.
Werksreset in Herstellerfirmware
1.2.99 geflashed - läuft.
2.0.12 geflashed - Fehler wie oben beschrieben. Zeigt Konfigversion 1.2.99. Zurückgesetzt. Zeigt Konfigversion 1.0.0
OTA-GD-Firmware-Update auf 1.2.460. Warten das geflashed. 100% - reboot - sicherheitshalber noch mal Powercycle - Fehler wie oben beschrieben.

Zurückgeflashed auf Herstellerversion.
Noch mal auf Werkseinstellungen gesetzt.
2.0.12 geflashed - Zeigt Konfigversion 1.0.0 - Fehler wie oben beschrieben
Einfach mal probehalber cranky16 OTA drübergebügelt - Fehler wie oben beschrieben

OTADowngrade auf 2.0.8 - Status wird wieder richtig dargestellt - gelb blinkend = wartend - Laden lässt sich aber nicht starten.

OTADowngrade auf 1.2.99 - Alles funktioniert wieder

## Expected behavior

Funktion wie 1.2.99

## Screenshots & Logfiles

[debug-report2_0_12-AC011K-10052205315112-2023-04-07T11-49-13-232.txt](https://github.com/warp-more-hardware/esp32-firmware/files/11178413/debug-report2_0_12-AC011K-10052205315112-2023-04-07T11-49-13-232.txt)
[debug-report2_0_8-AC011K-10052205315112-2023-04-07T12-10-10-645.txt](https://github.com/warp-more-hardware/esp32-firmware/files/11178414/debug-report2_0_8-AC011K-10052205315112-2023-04-07T12-10-10-645.txt)
[debug-report1_2_99-2023-04-07T10-56-32-478Z.txt](https://github.com/warp-more-hardware/esp32-firmware/files/11178415/debug-report1_2_99-2023-04-07T10-56-32-478Z.txt)

**Comment by bs-github** [comment]
Gelb blinken bedeutet Ladevorgang angefordert, aber kein Strom freigegeben.

Ist in deinem Setup neben der Wallbox noch anderes im Spiel?
Funktioniert das Laden vielleicht im Autostart modus ohne externe Steuerung?

Vielleicht sagt dir die Ladestromgrenzenanzeige was nicht passt.
<img width="1252" alt="Ladestromgrenzen" src="https://user-images.githubusercontent.com/1205454/230616348-f29ec041-d0a3-4c02-936b-a2d7e211b03b.png">

Kannst du bitte mit der 2.0.12 nochmal einen Ladevorgang komplett durchführen und dabei 2x den debug-report ziehen, 1 - wenns gelb blinkt, 2 - nach abstecken des autos?

**Comment by stpmuspro** [comment]
Nee, nix anderes im Spiel - hatte irgendwann mal evcc mit der 1.2.99 verbunden. 
Dann die Wallbox abgebaut und ins Ferienhaus gehangen.
Autostart oder Taster war bei mir auf freigegeben. Ist jetzt nach einmal Werkseinstellung laden wieder auf nicht aktiv. Ging anders nicht weg.

Angesteckt
[evse-debug-log-AC011K-10052205315112-2023-04-07T16-37-10-775.txt](https://github.com/warp-more-hardware/esp32-firmware/files/11179708/evse-debug-log-AC011K-10052205315112-2023-04-07T16-37-10-775.txt)

Ohne Auto
[evse-debug-log-AC011K-10052205315112-2023-04-07T16-53-35-341.txt](https://github.com/warp-more-hardware/esp32-firmware/files/11179712/evse-debug-log-AC011K-10052205315112-2023-04-07T16-53-35-341.txt)

**Comment by bs-github** [comment]
```
 2023-04-07 14:44:37,926  EVSE serial: SN10052205315112 hw: AC011K-AE-25-STL fw: 1.2.460 
 2023-04-07 14:44:37,926  EN+ GD EVSE Firmware Version or Hardware is not supported.
```
Das ist vermutlich der Knackpunkt.
Die Box meldet sich mit einer uns bisher nicht untergekommenen Kennung.

`-STL` ist neu.

Ich hab jetzt eine FW gebaut, die sie genauso behandelt wie die bekannten.
Kannst du auf eigene Gefahr ausprobieren: https://github.com/warp-more-hardware/esp32-firmware/commit/2bc90b8ffdee75f17d9febbc7f47e89408c443e0

[warpAC011K_firmware_2_0_12_64303acb_2bc90b8ffdee75f_AC011K-Ax-25-STL_merged.bin.zip](https://github.com/warp-more-hardware/esp32-firmware/files/11179982/warpAC011K_firmware_2_0_12_64303acb_2bc90b8ffdee75f_AC011K-Ax-25-STL_merged.bin.zip)

> Angesteckt [evse-debug-log-AC011K-10052205315112-2023-04-07T16-37-10-775.txt
](https://github.com/warp-more-hardware/esp32-firmware/files/11179708/evse-debug-log-AC011K-10052205315112-2023-04-07T16-37-10-775.txt)

Das Log ist voll mit MQTT Error Meldungen, da solltest du vielleicht mal schauen was dein MQTT Server der Box sendet.

**Comment by stpmuspro** [comment]
Perfekt, das wars wohl!
Läuft wieder...
Danke!

<img width="943" alt="Bildschirmfoto 2023-04-07 um 18 50 14" src="https://user-images.githubusercontent.com/62701963/230646766-77fb8e58-f83a-4f2d-9594-57d83067c250.png">

MQTT-Fehler kamen jetzt durch die ständigen Firmwarewechsel zustanden. Muss jetzt erst mal den Server wieder aufräumen.

**Comment by bs-github** [comment]
😃
